# Generated by Django 2.0 on 2018-04-10 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_auto_20180406_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerupdate',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 10, 16, 11, 48, 727166)),
        ),
    ]
