# Generated by Django 2.0 on 2018-04-11 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 4, 11, 21, 35, 8, 793882))),
                ('subject', models.CharField(choices=[('General', 'General Enquiries'), ('Listing', 'Get Listed on our website'), ('Partnership', 'Partnerships'), ('Media', 'Media'), ('Others', 'Others')], max_length=50)),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
