# Generated by Django 2.0 on 2018-03-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
