# Generated by Django 2.0 on 2018-04-06 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busses', '0002_auto_20180406_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerupdate',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 6, 22, 10, 48, 122123)),
        ),
    ]
