# Generated by Django 2.0 on 2018-04-11 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('short_description', models.CharField(max_length=2048)),
                ('description', models.TextField(null=True)),
                ('posted_on', models.DateTimeField(default=datetime.datetime(2018, 4, 11, 21, 14, 47, 30997))),
                ('image', models.ImageField(upload_to='campaigns/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='categories',
            field=models.ManyToManyField(related_name='campaigns', to='campaigns.Category'),
        ),
    ]
