# Generated by Django 2.0 on 2018-04-11 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_auto_20180411_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='user_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='user_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='posted_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 12, 2, 36, 17, 777996)),
        ),
    ]
