# Generated by Django 2.0 on 2018-04-11 21:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_auto_20180412_0236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('logo_image', models.ImageField(null=True, upload_to='organizations/')),
                ('url', models.URLField(max_length=512, null=True)),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 4, 12, 2, 41, 30, 872805))),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='campaign',
            name='posted_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 12, 2, 41, 30, 877808)),
        ),
        migrations.AddField(
            model_name='campaign',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='campaigns.Organization'),
        ),
    ]
