# Generated by Django 2.0 on 2018-02-04 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
                ('url', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='PriceTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('retailPrice', models.FloatField(default=0)),
                ('sellingPrice', models.FloatField(default=0)),
                ('specialPrice', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=500)),
                ('productUrl', models.URLField(max_length=500)),
                ('brand', models.CharField(max_length=50)),
                ('inStock', models.BooleanField(default=False)),
                ('codAvailable', models.BooleanField(default=False)),
                ('discountPercentage', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='products',
            field=models.ManyToManyField(to='shopping.Product'),
        ),
        migrations.AddField(
            model_name='imageurl',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Product'),
        ),
    ]
