# Generated by Django 2.0 on 2018-03-19 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('baseApiURL', models.URLField(blank=True, max_length=2500, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Store')),
            ],
        ),
    ]
