# Generated by Django 2.0 on 2018-04-03 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='cuelink_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
