# Generated by Django 2.0 on 2018-04-03 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_store_cuelink_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuelinkoffer',
            name='merchant',
        ),
        migrations.AddField(
            model_name='cuelinkoffer',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuelink_offers', to='shopping.Store'),
        ),
        migrations.AlterField(
            model_name='store',
            name='affiliate_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='affiliate_token',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='home_url',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
    ]
