# Generated by Django 2.0 on 2018-03-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_auto_20180320_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='catId',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
