# Generated by Django 2.0 on 2018-04-03 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_auto_20180404_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuelinkoffer',
            name='endTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='cuelinkoffer',
            name='startTime',
            field=models.DateTimeField(null=True),
        ),
    ]
