# Generated by Django 2.0 on 2018-03-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_category_catid'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='deltaGetURL',
            field=models.URLField(blank=True, max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='feedsListed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='last_updated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='topFeedsURL',
            field=models.URLField(blank=True, max_length=2500, null=True),
        ),
    ]
