# Generated by Django 2.0 on 2018-04-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_auto_20180404_0443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='store',
        ),
        migrations.AddField(
            model_name='category',
            name='store',
            field=models.ManyToManyField(related_name='categories', to='shopping.Store'),
        ),
    ]
