# Generated by Django 2.0 on 2018-04-06 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_auto_20180406_0347'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 4, 6, 22, 10, 48, 90879))),
                ('data_file', models.FileField(upload_to='data/cuelinks/offers/shopping/')),
            ],
        ),
    ]
