# Generated by Django 2.0 on 2018-03-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_auto_20180321_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
