# Generated by Django 2.0 on 2018-04-06 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_offerupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerupdate',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 6, 22, 23, 55, 955172)),
        ),
    ]
