# Generated by Django 2.0 on 2018-03-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_category_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='topSeller',
            field=models.BooleanField(default=False),
        ),
    ]
