# Generated by Django 2.0 on 2018-03-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_product_topseller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='version',
            new_name='current_version',
        ),
        migrations.AddField(
            model_name='category',
            name='last_version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
