# Generated by Django 2.0 on 2018-04-10 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_auto_20180406_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='DOTDUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 4, 10, 16, 11, 48, 695913))),
            ],
        ),
        migrations.AlterField(
            model_name='offerupdate',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 10, 16, 11, 48, 695913)),
        ),
    ]
