# Generated by Django 2.0 on 2018-03-22 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0010_store_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('retailPrice', models.FloatField(default=0)),
                ('sellingPrice', models.FloatField(default=0)),
                ('discountPercentage', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SearchProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=500)),
                ('productUrl', models.URLField(max_length=500)),
                ('brand', models.CharField(max_length=50)),
                ('inStock', models.BooleanField(default=False)),
                ('codAvailable', models.BooleanField(default=False)),
                ('topSeller', models.BooleanField(default=False)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Store')),
            ],
        ),
        migrations.AddField(
            model_name='productprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.SearchProduct'),
        ),
    ]
