# Generated by Django 2.0 on 2018-03-23 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0013_auto_20180324_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
                ('url', models.URLField(max_length=500)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.SearchProduct')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
