# Generated by Django 2.0 on 2018-03-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0014_searchproductimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='logo_image',
            field=models.ImageField(null=True, upload_to='stores/'),
        ),
    ]
