# Generated by Django 2.0 on 2018-03-30 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0015_store_logo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('link', models.URLField(max_length=2500)),
            ],
        ),
        migrations.AddField(
            model_name='searchproduct',
            name='catName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dotdimage',
            name='url',
            field=models.URLField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='offerimage',
            name='url',
            field=models.URLField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='url',
            field=models.URLField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='searchproductimage',
            name='url',
            field=models.URLField(max_length=2500),
        ),
        migrations.AddField(
            model_name='productlinks',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.SearchProduct'),
        ),
        migrations.AddField(
            model_name='productdescription',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.SearchProduct'),
        ),
    ]
